-- 9. BEFORE / AFTER VALIDATION TABLE
-- =========================================================

CREATE OR REPLACE TABLE
SNOWFLAKE_FINOPS.AUDIT.OPTIMIZATION_VALIDATION
(
    VALIDATION_ID VARCHAR,

    RECOMMENDATION_ID VARCHAR,

    ENTITY_TYPE VARCHAR,
    ENTITY_NAME VARCHAR,

    RECOMMENDATION_TYPE VARCHAR,

    BEFORE_CREDITS FLOAT,
    AFTER_CREDITS FLOAT,

    CREDITS_SAVED FLOAT,

    BEFORE_COST_USD FLOAT,
    AFTER_COST_USD FLOAT,

    USD_SAVED FLOAT,

    BEFORE_AVG_RUNTIME_SECONDS FLOAT,
    AFTER_AVG_RUNTIME_SECONDS FLOAT,

    PERFORMANCE_CHANGE_PERCENT FLOAT,

    VERIFICATION_STATUS VARCHAR,

    VALIDATED_AT TIMESTAMP
);


-- =========================================================
-- 10. VALIDATION VIEW
-- =========================================================

CREATE OR REPLACE VIEW
SNOWFLAKE_FINOPS.AUDIT.OPTIMIZATION_VALIDATION_SUMMARY
AS

SELECT

    VALIDATION_ID,

    RECOMMENDATION_ID,

    ENTITY_TYPE,
    ENTITY_NAME,

    RECOMMENDATION_TYPE,

    BEFORE_CREDITS,
    AFTER_CREDITS,

    CREDITS_SAVED,

    BEFORE_COST_USD,
    AFTER_COST_USD,

    USD_SAVED,

    BEFORE_AVG_RUNTIME_SECONDS,
    AFTER_AVG_RUNTIME_SECONDS,

    PERFORMANCE_CHANGE_PERCENT,

    VERIFICATION_STATUS,

    VALIDATED_AT

FROM
    SNOWFLAKE_FINOPS.AUDIT.OPTIMIZATION_VALIDATION;


-- =========================================================
-- 11. RECOMMENDATION ENGINE VIEW
-- =========================================================

CREATE OR REPLACE VIEW
SNOWFLAKE_FINOPS.RECOMMENDATIONS.RECOMMENDATION_ENGINE_SUMMARY
AS

SELECT

    RECOMMENDATION_ID,

    DETECTED_AT,

    ENTITY_TYPE,
    ENTITY_NAME,

    RECOMMENDATION_TYPE,
    SEVERITY,

    ROUND(
        CONFIDENCE_SCORE * 100,
        2
    ) AS CONFIDENCE_PERCENT,

    CURRENT_STATE,
    RECOMMENDED_STATE,

    REASON,
    EVIDENCE,

    ROUND(
        ESTIMATED_MONTHLY_CREDITS_SAVED,
        4
    ) AS ESTIMATED_MONTHLY_CREDITS_SAVED,

    ROUND(
        ESTIMATED_MONTHLY_USD_SAVED,
        2
    ) AS ESTIMATED_MONTHLY_USD_SAVED,

    IMPLEMENTATION_RISK,

    PRIORITY_SCORE,

    STATUS,

    VERIFICATION_STATUS,

    CREATED_BY,
    REVIEWED_BY,

    IMPLEMENTED_AT,
    VERIFIED_AT

FROM
    SNOWFLAKE_FINOPS.RECOMMENDATIONS.RECOMMENDATION_FACT;


-- =========================================================
-- 12. TOP 25 RECOMMENDATIONS
-- =========================================================

SELECT

    RECOMMENDATION_ID,

    RECOMMENDATION_TYPE,

    ENTITY_TYPE,
    ENTITY_NAME,

    CONFIDENCE_PERCENT,

    ESTIMATED_MONTHLY_CREDITS_SAVED,

    ESTIMATED_MONTHLY_USD_SAVED,

    IMPLEMENTATION_RISK,

    PRIORITY_SCORE,

    STATUS

FROM
    SNOWFLAKE_FINOPS.RECOMMENDATIONS.RECOMMENDATION_ENGINE_SUMMARY

ORDER BY

    PRIORITY_SCORE DESC,

    ESTIMATED_MONTHLY_USD_SAVED DESC

LIMIT 25;


-- =========================================================
-- 13. TOTAL POTENTIAL SAVINGS
-- =========================================================

SELECT

    COUNT(*) AS TOTAL_RECOMMENDATIONS,

    ROUND(
        SUM(
            ESTIMATED_MONTHLY_CREDITS_SAVED
        ),
        4
    ) AS TOTAL_ESTIMATED_MONTHLY_CREDITS_SAVED,

    ROUND(
        SUM(
            ESTIMATED_MONTHLY_USD_SAVED
        ),
        2
    ) AS TOTAL_ESTIMATED_MONTHLY_USD_SAVED,

    ROUND(
        AVG(CONFIDENCE_SCORE) * 100,
        2
    ) AS AVG_CONFIDENCE_PERCENT,

    ROUND(
        AVG(PRIORITY_SCORE),
        2
    ) AS AVG_PRIORITY_SCORE

FROM
    SNOWFLAKE_FINOPS.RECOMMENDATIONS.RECOMMENDATION_FACT;


-- =========================================================
-- 14. SUMMARY BY RECOMMENDATION TYPE
-- =========================================================

SELECT

    RECOMMENDATION_TYPE,

    COUNT(*) AS RECOMMENDATION_COUNT,

    ROUND(
        SUM(
            ESTIMATED_MONTHLY_CREDITS_SAVED
        ),
        4
    ) AS ESTIMATED_MONTHLY_CREDITS_SAVED,

    ROUND(
        SUM(
            ESTIMATED_MONTHLY_USD_SAVED
        ),
        2
    ) AS ESTIMATED_MONTHLY_USD_SAVED,

    ROUND(
        AVG(CONFIDENCE_SCORE) * 100,
        2
    ) AS AVG_CONFIDENCE_PERCENT,

    ROUND(
        AVG(PRIORITY_SCORE),
        2
    ) AS AVG_PRIORITY_SCORE

FROM
    SNOWFLAKE_FINOPS.RECOMMENDATIONS.RECOMMENDATION_FACT

GROUP BY
    RECOMMENDATION_TYPE

ORDER BY
    ESTIMATED_MONTHLY_USD_SAVED DESC;



USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FINOPS_WH;
USE DATABASE SNOWFLAKE_FINOPS;

SELECT
    COLUMN_NAME,
    DATA_TYPE,
    ORDINAL_POSITION
FROM SNOWFLAKE_FINOPS.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'RECOMMENDATIONS'
  AND TABLE_NAME = 'OPTIMIZATION_RECOMMENDATIONS_CLEAN'
ORDER BY ORDINAL_POSITION;


-- ============================================================
