---- Check for Telementory

SELECT COUNT(*) AS QUERY_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;

SELECT COUNT(*) AS WAREHOUSE_METERING_ROWS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY;

SELECT COUNT(*) AS WAREHOUSE_LOAD_ROWS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY;




CREATE OR REPLACE TABLE SNOWFLAKE_FINOPS.RAW.QUERY_HISTORY_RAW AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE SNOWFLAKE_FINOPS.RAW.WAREHOUSE_METERING_RAW AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE SNOWFLAKE_FINOPS.RAW.WAREHOUSE_LOAD_RAW AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_LOAD_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP());




