-- 4. QUERY PERFORMANCE ANALYSIS
-- =========================================================

CREATE OR REPLACE TABLE SNOWFLAKE_FINOPS.ANALYTICS.QUERY_PERFORMANCE AS

SELECT
    WAREHOUSE_NAME,

    COUNT(*) AS TOTAL_QUERIES,

    COUNT_IF(
        EXECUTION_STATUS = 'SUCCESS'
    ) AS SUCCESSFUL_QUERIES,

    COUNT_IF(
        EXECUTION_STATUS <> 'SUCCESS'
    ) AS FAILED_QUERIES,

    ROUND(
        AVG(TOTAL_ELAPSED_TIME) / 1000,
        2
    ) AS AVG_ELAPSED_SECONDS,

    ROUND(
        MAX(TOTAL_ELAPSED_TIME) / 1000,
        2
    ) AS MAX_ELAPSED_SECONDS,

    ROUND(
        AVG(BYTES_SCANNED) / POWER(1024, 3),
        2
    ) AS AVG_GB_SCANNED,

    ROUND(
        SUM(BYTES_SCANNED) / POWER(1024, 3),
        2
    ) AS TOTAL_GB_SCANNED,

    ROUND(
        AVG(PERCENTAGE_SCANNED_FROM_CACHE),
        2
    ) AS AVG_CACHE_PERCENT,

    ROUND(
        AVG(
            CASE
                WHEN PARTITIONS_TOTAL > 0
                THEN (PARTITIONS_SCANNED / PARTITIONS_TOTAL) * 100
            END
        ),
        2
    ) AS AVG_PARTITION_SCAN_PERCENT,

    ROUND(
        SUM(BYTES_SPILLED_TO_LOCAL_STORAGE) / POWER(1024, 3),
        2
    ) AS TOTAL_LOCAL_SPILL_GB,

    ROUND(
        SUM(BYTES_SPILLED_TO_REMOTE_STORAGE) / POWER(1024, 3),
        2
    ) AS TOTAL_REMOTE_SPILL_GB,

    ROUND(
        AVG(QUEUED_OVERLOAD_TIME) / 1000,
        2
    ) AS AVG_QUEUE_OVERLOAD_SECONDS

FROM SNOWFLAKE_FINOPS.CORE.QUERY_HISTORY

GROUP BY
    WAREHOUSE_NAME;


-- =========================================================
-- 5. EXPENSIVE / HEAVY QUERY CANDIDATES
-- =========================================================

CREATE OR REPLACE TABLE SNOWFLAKE_FINOPS.ANALYTICS.HEAVY_QUERIES AS

SELECT
    QUERY_ID,
    WAREHOUSE_NAME,
    USER_NAME,
    START_TIME,

    ROUND(TOTAL_ELAPSED_TIME / 1000, 2)
        AS ELAPSED_SECONDS,

    ROUND(BYTES_SCANNED / POWER(1024, 3), 2)
        AS GB_SCANNED,

    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,

    CASE
        WHEN PARTITIONS_TOTAL > 0
        THEN ROUND(
            (PARTITIONS_SCANNED / PARTITIONS_TOTAL) * 100,
            2
        )
    END AS PARTITION_SCAN_PERCENT,

    PERCENTAGE_SCANNED_FROM_CACHE,

    ROUND(
        BYTES_SPILLED_TO_LOCAL_STORAGE / POWER(1024, 3),
        2
    ) AS LOCAL_SPILL_GB,

    ROUND(
        BYTES_SPILLED_TO_REMOTE_STORAGE / POWER(1024, 3),
        2
    ) AS REMOTE_SPILL_GB,

    EXECUTION_STATUS,

    QUERY_TEXT

FROM SNOWFLAKE_FINOPS.CORE.QUERY_HISTORY

WHERE
    TOTAL_ELAPSED_TIME >= 10000
    OR BYTES_SCANNED >= 1024 * 1024 * 1024
    OR BYTES_SPILLED_TO_LOCAL_STORAGE > 0
    OR BYTES_SPILLED_TO_REMOTE_STORAGE > 0

ORDER BY
    TOTAL_ELAPSED_TIME DESC;


-- =========================================================
-- 6. FAILED QUERY ANALYSIS
-- =========================================================

CREATE OR REPLACE TABLE SNOWFLAKE_FINOPS.ANALYTICS.FAILED_QUERIES AS

SELECT
    QUERY_ID,
    WAREHOUSE_NAME,
    USER_NAME,
    START_TIME,

    EXECUTION_STATUS,
    ERROR_CODE,
    ERROR_MESSAGE,

    TOTAL_ELAPSED_TIME,

    QUERY_TEXT

FROM SNOWFLAKE_FINOPS.CORE.QUERY_HISTORY

WHERE EXECUTION_STATUS <> 'SUCCESS'

ORDER BY START_TIME DESC;


-- =========================================================
-- 7. QUERY FREQUENCY ANALYSIS
-- =========================================================

USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE SNOWFLAKE_FINOPS.ANALYTICS.QUERY_FREQUENCY AS

SELECT
    WAREHOUSE_NAME,

    DATABASE_NAME,
    SCHEMA_NAME,

    USER_NAME,

    QUERY_TYPE,

    COUNT(*) AS EXECUTION_COUNT,

    ROUND(
        AVG(TOTAL_ELAPSED_TIME) / 1000,
        2
    ) AS AVG_EXECUTION_SECONDS,

    ROUND(
        SUM(BYTES_SCANNED) / POWER(1024, 3),
        2
    ) AS TOTAL_GB_SCANNED

FROM SNOWFLAKE_FINOPS.CORE.QUERY_HISTORY

GROUP BY
    WAREHOUSE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    USER_NAME,
    QUERY_TYPE;


-- =========================================================
-- 8. WAREHOUSE COST SUMMARY
-- =========================================================

CREATE OR REPLACE VIEW SNOWFLAKE_FINOPS.ANALYTICS.WAREHOUSE_COST_SUMMARY AS

SELECT
    WAREHOUSE_NAME,

    SUM(TOTAL_CREDITS) AS TOTAL_CREDITS,

    ROUND(
        SUM(ESTIMATED_COST_USD),
        2
    ) AS TOTAL_ESTIMATED_COST_USD,

    MIN(USAGE_DATE) AS FIRST_USAGE_DATE,
    MAX(USAGE_DATE) AS LAST_USAGE_DATE,

    COUNT(DISTINCT USAGE_DATE) AS ACTIVE_DAYS

FROM SNOWFLAKE_FINOPS.ANALYTICS.DAILY_WAREHOUSE_COST

GROUP BY WAREHOUSE_NAME;


-- =========================================================
-- 9. VALIDATION
-- =========================================================

SELECT *
FROM SNOWFLAKE_FINOPS.ANALYTICS.DAILY_WAREHOUSE_COST
ORDER BY USAGE_DATE DESC, TOTAL_CREDITS DESC;


SELECT *
FROM SNOWFLAKE_FINOPS.ANALYTICS.QUERY_PERFORMANCE
ORDER BY TOTAL_QUERIES DESC;


SELECT *
FROM SNOWFLAKE_FINOPS.ANALYTICS.HEAVY_QUERIES
LIMIT 20;


SELECT *
FROM SNOWFLAKE_FINOPS.ANALYTICS.FAILED_QUERIES
LIMIT 20;


SELECT *
FROM SNOWFLAKE_FINOPS.ANALYTICS.QUERY_FREQUENCY
ORDER BY EXECUTION_COUNT DESC
LIMIT 20;


SELECT *
FROM SNOWFLAKE_FINOPS.ANALYTICS.WAREHOUSE_COST_SUMMARY;




