

USE ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_FINOPS.STREAMLIT;

GRANT USAGE ON DATABASE SNOWFLAKE_FINOPS TO ROLE FINOPS_VIEWER;
GRANT USAGE ON SCHEMA SNOWFLAKE_FINOPS.STREAMLIT TO ROLE FINOPS_VIEWER;